
#debug: true
logging:
  level: 
    pers.abaneo.xnote.api.dao: debug
    
server:
  port: 14000
spring:
  profiles:active: dev
  application:
    name: xnote
  redis:
    database: 1
    hostname: 47.94.106.96
    port: 6379
    password: 1124@redis
    pool.max-active: 8
    pool.max-idle: 8
    pool.min-idle: 0
    pool.max-wait: -1
    timeout: 0
  datasource:
    url: jdbc:mysql://47.94.106.96:3306/xnote?useUnicode=true&characterEncoding=utf-8
    username: mysql
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
#    prefix: /fk/
#    request-context-attribute: 
#    settings.*: 
    suffix: .html
#    template-loader-path: classpath:/templates/
#    view-names:  # whitelist of view names that can be resolved
    
mybatis:
  config-locations: classpath*:mybatis-config.xml
  mapper-locations: classpath*:pers/abaneo/xnote/dao/mapper/*.xml
  
file:
  upload:
    path: /home/data/xnote/upload
    